### ISSUE TITLE
What's in scope?

### ISSUE THREAD

**Issue by matt-dray** [matt-dray/quartostamp#4]
So far I've included divs, classes, etc, that are inserted into the body of your document.

So far I haven't included anything that could be added to the YAML of a Quarto document. Should I? How would these be inserted? For example, setting a theme requires:

```
title: 'Title'
subtitle: 'Subtitle'
author: 'Firstname Lastname'
format:
  revealjs: 
    theme: custom.scss
```

Would the function insert that whole fenced chunk? Just the `format` chunk? Or just the `theme` line? Should the line be preemptively indented?

I think anything that's strictly of the realm of R Markdown should be included. We have {remedy} for that. Equally this isn't a place for {knitr}-chunk options (which are now autocompleted in RStudio anyway).

Anything else?
